version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: Postgres_Container
    env_file:
      - .env.dev.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: RoboAdvisor_Container
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
      - .env.oauth
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

volumes:
  postgres_data: