version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn robo_advisor_project.wsgi:application --bind 0.0.0.0:8000
    container_name: RoboAdvisor_Container
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:15.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: Postgres_Container
    env_file:
      - .env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/mediafiles
    ports:
      - '1337:80'
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: