version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: Postgres_Container
    restart: always
    environment:
      - POSTGRES_DB=robo_advisor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - web_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: RoboAdvisor_Container
    restart: always
    ports:
      - '8000:8000'
    environment:
    - DEBUG=1
    - POSTGRES_HOST=db
    - POSTGRES_PORT=5432
    - POSTGRES_DB=robo_advisor
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - DATABASE=postgres
    - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    - CSRF_TRUSTED_ORIGINS=http://localhost:1337
    env_file:
      - .env.oauth
    volumes:
      - .:/usr/src/app/
    networks:
      - web_network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  web_network: