version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: Postgres_Container
    env_file:
      - .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn robo_advisor_project.wsgi:application --bind 0.0.0.0:8000
    container_name: RoboAdvisor_Container
    expose:
      - 8000
    env_file:
      - .env.prod
      - .env.oauth
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/mediafiles
    depends_on:
      - db
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: NginxProxy_Container
    restart: always
    ports:
      - '1337:80'
      - '443:443'
    environment:
      - TRUST_DOWNSTREAM_PROXY=false
    volumes:
      - static_volume:/home/web/app/staticfiles
      - media_volume:/home/web/app/mediafiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: