# Generated by Django 4.2.4 on 2023-08-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_range",
                    models.CharField(
                        choices=[
                            ("RANGE1", "RANGE1"),
                            ("RANGE2", "RANGE2"),
                            ("RANGE3", "RANGE3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "investment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="investment.investment",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics",
                "verbose_name_plural": "Analytics",
                "db_table": "Analytics",
            },
        ),
    ]
