# Generated by Django 4.2.2 on 2023-07-31 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investment_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="investmentportfolio",
            unique_together={("user", "name")},
        ),
    ]
