# Generated by Django 4.2.3 on 2023-07-28 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('starting_investment_amount', models.IntegerField()),
                ('stocks_symbols', models.CharField(max_length=500)),
                ('stocks_weights', models.CharField(max_length=500)),
                ('sectors_names', models.CharField(max_length=500)),
                ('sectors_weights', models.CharField(max_length=500)),
                ('annual_returns', models.FloatField()),
                ('annual_max_loss', models.FloatField()),
                ('annual_volatility', models.FloatField()),
                ('annual_sharpe', models.FloatField()),
                ('total_change', models.FloatField()),
                ('monthly_change', models.FloatField()),
                ('daily_change', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'InvestorUser',
            },
        ),
    ]
