# Generated by Django 4.2.3 on 2023-07-27 23:45

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferencesB',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('starting_investment_amount', models.IntegerField()),
                ('stocks_symbols', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('stocks_weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('sectors_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('sectors_weights', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('annual_returns', models.FloatField()),
                ('annual_max_loss', models.FloatField()),
                ('annual_volatility', models.FloatField()),
                ('annual_sharpe', models.FloatField()),
                ('total_change', models.FloatField()),
                ('monthly_change', models.FloatField()),
                ('daily_change', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPreferencesB',
            },
        ),
        migrations.CreateModel(
            name='UserPreferencesA',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_answer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_answer', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPreferencesA',
            },
        ),
    ]
