name: PostgreSQL, PyTest & Flake8
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Pre-installation of docker-compose
      run: |
        sudo apt-get install python3-dev libyaml-dev
    - name: Upgrade pip
      run: |
        pip install --upgrade pip
    - name: Install docker-compose
      run: |
        pip install drf-spectacular==0.26.4 pyyaml==5.3.1 docker-compose
    - name: Run Flake8 Linter
      run: |
        docker-compose run --rm web sh -c "flake8 --max-line-length 120 --ignore=E402,F401 --exclude=venv ."
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
    - name: Test with PyTest
      run: |
        docker-compose run --rm app sh -c "pytest -s -v"
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
