name: PostgreSQL, PyTest & Flake8
on: pull_request
jobs:
  # Label of the container job
  setup-database:
    # Containers must run in Linux based operating systems
    name: Setup PostgreSQL Database
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
        - name: Wait for PostgreSQL to start
        run: |
          sleep 1

  flake8-and-pytest:
    # Containers must run in Linux based operating systems
    name: Check code with Flake8, then run the application's tests with PyTest
    runs-on: ubuntu-latest 
    needs: setup-database
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: python -m pipenv sync
      - name: Install dependencies from requirements.txt
        run: python -m pip install -r requirements.txt
        # Linter
      - name: Run Flake8
        run: python3.11 -m pipenv run flake8 --max-line-length 120 --ignore=E402,F401 --exclude=venv .
      - name: Run Migrations
        run: python manage.py migrate
        # Tests
      - name: Run PyTest
        run: python3.11 -m pipenv run pytest -v
