name: PostgreSQL, PyTest & Flake8
on: pull_request
jobs:
  setup-database:
    name: Setup PostgreSQL Database
    runs-on: ubuntu-20.04
    container: fedora:34
    env:
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Install PostgreSQL client tools
        run: dnf install -y postgresql
      - name: Execute SQL Queries
        run: |
          psql \
            --host=$POSTGRES_HOST \
            --port=$POSTGRES_PORT \
            --dbname=$POSTGRES_DB \
            --username=$POSTGRES_USER \
            --password=$POSTGRES_PASSWORD \
            --command="SELECT * FROM your_table_name;"
        # Add more SQL commands or queries as needed

  pytest:
    name: Run the application's tests with PyTest
    runs-on: ubuntu-20.04
    container: fedora:34
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    steps:
      - name: Install Pipenv and git
        run: dnf install -y pipenv git
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: pipenv sync --dev
      - name: Run PyTest
        run: pipenv run pytest -v
  flake8:
    name: Check code with Flake8
    runs-on: ubuntu-20.04
    container: fedora:34
    steps:
      - name: Install Pipenv and Git
        run: dnf install -y pipenv git
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup environment
        run: pipenv sync --dev
      - name: Run Flake8
        run: pipenv run flake8 --max-line-length 120 --ignore=E402,F401