name: PostgreSQL, PyTest & Flake8
on: pull_request
jobs:
  setup-database:
    name: Setup PostgreSQL Database
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Wait for PostgreSQL to start
        run: |
          sleep 10
      - name: Run Migrations
        run: |
          python manage.py migrate

  pytest:
    name: Run the application's tests with PyTest, then check code with Flake8
    runs-on: ubuntu-latest
    container: fedora:34
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    needs: setup-database
    steps:
      - name: Install Pipenv and git
        run: dnf install -y pipenv git
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup environment
        run: pipenv sync --dev
      - name: Run PyTest
        run: pipenv run pytest -v
      - name: Run Flake8
        run: pipenv run flake8 --max-line-length 120 --ignore=E402,F401 --exclude=venv .
